import type { Sacco, SaccoConfig } from '@saccosphere/schemas'

export const MOCK_SACCOS: Sacco[] = [
  {
    id: 'sacco-001',
    slug: 'stima-sacco',
    name: 'Stima SACCO',
    sector: 'Energy',
    county: 'Nairobi',
    initials: 'ST',
    color: '#0070ba',
    membership_type: 'open',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/001/2006',
    description: 'Serving Kenya Power employees and the wider energy sector since 2006.',
    member_count: 4821,
    loan_rate_pct: 12,
    loan_multiplier: 3,
    established_year: 2006,
  },
  {
    id: 'sacco-002',
    slug: 'teachers-sacco',
    name: 'Teachers SACCO',
    sector: 'Education',
    county: 'Nairobi',
    initials: 'TS',
    color: '#7c3aed',
    membership_type: 'open',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/022/2008',
    description: 'Empowering educators across Kenya since 2008.',
    member_count: 28012,
    loan_rate_pct: 10.5,
    loan_multiplier: 3,
    established_year: 2008,
  },
  {
    id: 'sacco-003',
    slug: 'unaitas-sacco',
    name: 'Unaitas SACCO',
    sector: 'Community',
    county: "Murang'a",
    initials: 'UN',
    color: '#16a085',
    membership_type: 'open',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/080/2010',
    description: "One of Kenya's largest and most trusted community SACCOs.",
    member_count: 62440,
    loan_rate_pct: 12,
    loan_multiplier: 4,
    established_year: 1993,
  },
  {
    id: 'sacco-004',
    slug: 'kenya-police-sacco',
    name: 'Kenya Police SACCO',
    sector: 'Government',
    county: 'Nationwide',
    initials: 'KP',
    color: '#c0392b',
    membership_type: 'staff_only',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/045/2012',
    description: 'Serving Kenya National Police Service members and their families.',
    member_count: 35200,
    loan_rate_pct: 11,
    loan_multiplier: 3,
    established_year: 2012,
  },
  {
    id: 'sacco-005',
    slug: 'imarika-sacco',
    name: 'Imarika SACCO',
    sector: 'Community',
    county: 'Kilifi',
    initials: 'IK',
    color: '#2980b9',
    membership_type: 'open',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/091/2015',
    description: 'Rooted in the Coast region, growing Kenya together.',
    member_count: 18003,
    loan_rate_pct: 12.5,
    loan_multiplier: 3,
    established_year: 2015,
  },
  {
    id: 'sacco-006',
    slug: 'safaricom-sacco',
    name: 'Safaricom SACCO',
    sector: 'Telecoms',
    county: 'Nairobi',
    initials: 'SF',
    color: '#00a550',
    membership_type: 'staff_only',
    status: 'active',
    sasra_reg_no: 'SASRA/DT/112/2018',
    description: 'Exclusively for Safaricom PLC employees and contractors.',
    member_count: 5400,
    loan_rate_pct: 10.5,
    loan_multiplier: 3,
    established_year: 2018,
  },
]

// Per-SACCO dynamic configurations — different fields, docs, and loan products per SACCO
export const MOCK_SACCO_CONFIGS: Record<string, SaccoConfig> = {
  'stima-sacco': {
    membership: {
      min_age: 18,
      min_monthly_contribution_kes: 1000,
      registration_fee_kes: 1000,
      min_share_capital_kes: 5000,
      required_documents: [
        { key: 'national_id_front', label: 'National ID — Front', required: true, already_verified_from_kyc: true },
        { key: 'national_id_back', label: 'National ID — Back', required: true, already_verified_from_kyc: true },
        { key: 'passport_photo', label: 'Passport photo', required: true, already_verified_from_kyc: true },
        { key: 'payslip', label: 'Latest payslip (last 3 months)', required: true, hint: 'Must show employer name and gross salary' },
        { key: 'bank_statement', label: 'Bank statement (3 months)', required: false, accepted_formats: ['application/pdf'] },
      ],
      additional_fields: [
        { key: 'employer_name', label: 'Employer / Company name', type: 'text', required: true, placeholder: 'e.g. Kenya Power & Lighting Co.' },
        { key: 'employee_number', label: 'Employee number', type: 'text', required: true, placeholder: 'e.g. KP-12345' },
        { key: 'gross_salary', label: 'Gross monthly salary (KES)', type: 'number', required: true, min: 10000 },
        { key: 'employment_type', label: 'Employment type', type: 'select', required: true, options: ['Permanent', 'Contract', 'Casual'] },
        { key: 'years_employed', label: 'Years at current employer', type: 'number', required: true, min: 0, max: 50 },
      ],
    },
    loan_products: [
      {
        key: 'development',
        label: 'Development loan',
        description: 'For home improvement, education, or business growth',
        interest_rate_pct: 12,
        max_multiplier: 3,
        min_months: 6,
        max_months: 48,
        min_guarantors: 2,
        processing_fee_pct: 0.5,
        disbursement_options: ['mpesa', 'fosa', 'bank'],
      },
      {
        key: 'emergency',
        label: 'Emergency loan',
        description: 'Quick funds for unexpected needs — approved within 24 hours',
        interest_rate_pct: 10,
        max_multiplier: 1,
        min_months: 1,
        max_months: 12,
        min_guarantors: 0,
        processing_fee_pct: 0,
        disbursement_options: ['mpesa'],
      },
      {
        key: 'school_fees',
        label: 'School fees loan',
        description: 'Paid directly to the institution or to your M-Pesa',
        interest_rate_pct: 10,
        max_multiplier: 2,
        min_months: 3,
        max_months: 12,
        min_guarantors: 1,
        processing_fee_pct: 0,
        disbursement_options: ['mpesa', 'bank'],
      },
    ],
    payments: {
      mpesa_paybill: '123456',
      mpesa_shortcode: '123456',
      accepted_methods: ['mpesa', 'bank_transfer'],
    },
    contributions: {
      deduction_day: 25,
      grace_period_days: 5,
      allow_top_up: true,
    },
    display: {
      primary_color: '#0070ba',
      show_bosa: true,
      show_fosa: true,
      show_share_capital: true,
      account_labels: { bosa: 'BOSA savings', fosa: 'FOSA savings', shares: 'Share capital' },
    },
  },

  'teachers-sacco': {
    membership: {
      min_age: 18,
      min_monthly_contribution_kes: 500,
      registration_fee_kes: 500,
      min_share_capital_kes: 3000,
      required_documents: [
        { key: 'national_id_front', label: 'National ID — Front', required: true, already_verified_from_kyc: true },
        { key: 'national_id_back', label: 'National ID — Back', required: true, already_verified_from_kyc: true },
        { key: 'passport_photo', label: 'Passport photo', required: true, already_verified_from_kyc: true },
        { key: 'tsc_number', label: 'TSC Certificate / Letter', required: true, hint: 'Teachers Service Commission registration' },
      ],
      additional_fields: [
        { key: 'tsc_number', label: 'TSC number', type: 'text', required: true, placeholder: 'e.g. TSC/123456' },
        { key: 'school_name', label: 'School / Institution name', type: 'text', required: true },
        { key: 'county_of_posting', label: 'County of posting', type: 'select', required: true,
          options: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Other'] },
        { key: 'gross_salary', label: 'Gross monthly salary (KES)', type: 'number', required: true, min: 5000 },
      ],
    },
    loan_products: [
      {
        key: 'development',
        label: 'Development loan',
        interest_rate_pct: 10.5,
        max_multiplier: 3,
        min_months: 6,
        max_months: 36,
        min_guarantors: 2,
        processing_fee_pct: 0.5,
        disbursement_options: ['mpesa', 'fosa', 'bank'],
      },
      {
        key: 'emergency',
        label: 'Emergency loan',
        interest_rate_pct: 9,
        max_multiplier: 1,
        min_months: 1,
        max_months: 6,
        min_guarantors: 0,
        processing_fee_pct: 0,
        disbursement_options: ['mpesa'],
      },
    ],
    payments: {
      mpesa_paybill: '654321',
      mpesa_shortcode: '654321',
      accepted_methods: ['mpesa', 'bank_transfer'],
    },
    contributions: {
      deduction_day: 28,
      grace_period_days: 3,
      allow_top_up: false,
    },
    display: {
      primary_color: '#7c3aed',
      show_bosa: true,
      show_fosa: false,
      show_share_capital: true,
      account_labels: { bosa: 'Savings', fosa: 'Current', shares: 'Shares' },
    },
  },

  'unaitas-sacco': {
    membership: {
      min_age: 18,
      min_monthly_contribution_kes: 1000,
      registration_fee_kes: 1000,
      min_share_capital_kes: 5000,
      required_documents: [
        { key: 'national_id_front', label: 'National ID — Front', required: true, already_verified_from_kyc: true },
        { key: 'national_id_back', label: 'National ID — Back', required: true, already_verified_from_kyc: true },
        { key: 'passport_photo', label: 'Passport photo', required: true, already_verified_from_kyc: true },
        { key: 'payslip', label: 'Latest payslip', required: true },
        { key: 'bank_statement', label: 'Bank statement (3 months)', required: true },
      ],
      additional_fields: [
        { key: 'employer_name', label: 'Employer / Business name', type: 'text', required: true },
        { key: 'gross_salary', label: 'Gross monthly income (KES)', type: 'number', required: true, min: 5000 },
        { key: 'employment_type', label: 'Employment type', type: 'select', required: true,
          options: ['Employed — salaried', 'Self employed', 'Business owner', 'Farmer'] },
        { key: 'next_of_kin_name', label: 'Next of kin — full name', type: 'text', required: true },
        { key: 'next_of_kin_phone', label: 'Next of kin — phone number', type: 'phone', required: true },
      ],
    },
    loan_products: [
      {
        key: 'development',
        label: 'Development loan',
        interest_rate_pct: 12,
        max_multiplier: 4,
        min_months: 6,
        max_months: 60,
        min_guarantors: 2,
        processing_fee_pct: 1,
        disbursement_options: ['mpesa', 'bank'],
      },
      {
        key: 'emergency',
        label: 'Emergency loan',
        interest_rate_pct: 10,
        max_multiplier: 1,
        min_months: 1,
        max_months: 12,
        min_guarantors: 0,
        processing_fee_pct: 0,
        disbursement_options: ['mpesa'],
      },
    ],
    payments: {
      mpesa_paybill: '789012',
      accepted_methods: ['mpesa', 'airtel', 'bank_transfer'],
    },
    contributions: {
      deduction_day: 25,
      grace_period_days: 7,
      allow_top_up: true,
    },
    display: {
      primary_color: '#16a085',
      show_bosa: true,
      show_fosa: true,
      show_share_capital: true,
      account_labels: { bosa: 'Savings', fosa: 'Current account', shares: 'Share capital' },
    },
  },
}
